<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

# Neural Networks

## *Data Science Unit 4 Sprint 2 Assignment 1*

## Define the Following:
You can add image, diagrams, whatever you need to ensure that you understand the concepts below.

### Input Layer:
- This is the inpout from the dataset and is sometimes called the visible layer.

### Hidden Layer:
- The layer or layers that come after the input layer and the user has no direct interaction with them. 
  They perform their functions and then pass it onto either the next hidden layer or the output layer.
 
### Output Layer:
- This is the final layer that ouputs a vector of values that show what the actual prediction for the function is.

### Neuron:
- Or the nodes are what receive inputs from the previous layer or the dataset and then give outputs for either 
  the entire function or for the next layer to use.

### Weight:
- The weight show how important the output for each node plays in determining the output of the function.

### Activation Function:
- The function that modifies the output of the function so that it is understandable to humans. 
  These can also be used to convert the output of one layer to be usable by the next hidden layer.

### Node Map:
- The Node Map is a visual diagram that shows how the neural network works. How the outputs of of node move on to 
  the next node so that you can have an idea of how it works.

### Perceptron:
- The simplest king of neural network that only has a single node that can take any number of inputs and spit out 
  an output.

## Inputs -> Outputs

### Explain the flow of information through a neural network from inputs to outputs. Be sure to include: inputs, weights, bias, and activation functions. How does it all flow from beginning to end?

#### Your Answer Here
The information starts out in the dataset and and is put into the input layer of the neural network the network then takes that information and uses an activation function to pass it to the first hidden layer where it is multiplied by the weight and then passed to the next hidden layer until it hits the output layer where it adds the bias and the spits out a human readable prediction.

## Write your own perceptron code that can correctly classify (99.0% accuracy) a NAND gate. 

| x1 | x2 | y |
|----|----|---|
| 0  | 0  | 1 |
| 1  | 0  | 1 |
| 0  | 1  | 1 |
| 1  | 1  | 0 |

In [1]:
import pandas as pd
import numpy as np
np.random.seed(777)

data = { 'x1': [0,1,0,1],
         'x2': [0,0,1,1],
         'y':  [1,1,1,0]
       }

df = pd.DataFrame.from_dict(data).astype('int')
df.values

array([[0, 0, 1],
       [1, 0, 1],
       [0, 1, 1],
       [1, 1, 0]])

In [2]:
##### Your Code Here #####

# define the sigmoid and its derivative
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    sx = sigmoid(x)
    return sx * (1 - sx)

In [8]:
# Initialize the random weights for the inputs
weights = 2 * np.random.random((2,1)) - 1
weights

array([[0.8539941 ],
       [0.45397797]])

In [10]:
# separate the inputs from the output
inputs = df[["x1","x2"]]
correct_out = [[1],[1],[1],[0]]

In [42]:
# create a for loop to update our weights 1,000 times
for iteration in range(1000):
    # weighted sum of inputs / weights
    weighted_sum = np.dot(inputs, weights) + 7
    # activate
    activated_output = sigmoid(weighted_sum)
    # calculate error
    error = correct_out - activated_output
    adjustments = error * sigmoid_derivative(weighted_sum)
    # Update the weights
    weights += np.dot(inputs.T, adjustments)
#     breakpoint()
    
print("Weights after training")
print(weights)

print("Output after training")
print(activated_output)

Weights after training
[[-4.66666664]
 [-4.66666664]]
Output after training
[[0.99908895]
 [0.91160033]
 [0.91160033]
 [0.08839968]]


## Implement your own Perceptron Class and use it to classify a binary dataset: 
- [The Pima Indians Diabetes dataset](https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv) 

You may need to search for other's implementations in order to get inspiration for your own. There are *lots* of perceptron implementations on the internet with varying levels of sophistication and complexity. Whatever your approach, make sure you understand **every** line of your implementation and what its purpose is.

In [12]:
diabetes = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv')
diabetes.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

Although neural networks can handle non-normalized data, scaling or normalizing your data will improve your neural network's learning speed. Try to apply the sklearn `MinMaxScaler` or `Normalizer` to your diabetes dataset. 

In [22]:
from sklearn.preprocessing import MinMaxScaler, Normalizer

feats = list(diabetes)[:-1]

X = diabetes[feats]
y = diabetes['Outcome']
transformer = Normalizer().fit(X)
X = pd.DataFrame(transformer.transform(X))
X.columns = feats
X.head()

Pregnancies   Glucose  BloodPressure  SkinThickness   Insulin       BMI  \
0     0.033552  0.827625       0.402628       0.195722  0.000000  0.187893   
1     0.008424  0.716040       0.555984       0.244296  0.000000  0.224079   
2     0.040398  0.924097       0.323181       0.000000  0.000000  0.117658   
3     0.006612  0.588467       0.436392       0.152076  0.621527  0.185797   
4     0.000000  0.596386       0.174127       0.152361  0.731335  0.187622   

   DiabetesPedigreeFunction       Age  
0                  0.003506  0.279603  
1                  0.002957  0.261144  
2                  0.003393  0.161591  
3                  0.001104  0.138852  
4                  0.009960  0.143655

In [52]:
y = np.array(y).reshape(768,1)

In [114]:
##### Update this Class #####

class Perceptron:
    
    def __init__(self, niter = 10):
        self.niter = niter
    
    def __sigmoid(self, x):
        return 1 / (1 + np.exp(-x))
    
    def __sigmoid_derivative(self, x):
        sx = sigmoid(x)
        return sx * (1 - sx)

    def fit(self, X, y):
        """Fit training data
        X : Training vectors, X.shape : [#samples, #features]
        y : Target values, y.shape : [#samples]
        """
        
        # Randomly Initialize Weights
        weights = 2 * np.random.random((len(X.columns),1)) - 1

        for i in range(self.niter):
            # Weighted sum of inputs / weights
            weighted_sum = np.dot(X, weights) + 11
            # Activate!
            activated_output = sigmoid(weighted_sum)
            # Cac error
            error = y - activated_output
            adjustments = error * sigmoid_derivative(weighted_sum)
            # Update the Weights
            weights += np.dot(X.T, adjustments)
            
        self.weights = weights
        self.activated_output = activated_output

    def predict(self, X):
        """Return class label after unit step"""
        print(self.activated_output)
        

In [115]:
perceptron = Perceptron(200)
perceptron.fit(X,y)
perceptron.predict(X)

[[1.43434631e-12]
 [4.53861960e-13]
 [1.34329590e-11]
 [9.43832408e-12]
 [1.79758764e-09]
 [8.08195571e-13]
 [2.54541060e-11]
 [3.53799913e-09]
 [1.39961663e-05]
 [1.56104329e-12]
 [4.60108351e-13]
 [3.34702206e-12]
 [1.14584895e-12]
 [1.59283472e-03]
 [1.24481403e-10]
 [2.89181171e-09]
 [7.92166059e-09]
 [6.00593141e-13]
 [5.13302706e-11]
 [3.15354571e-12]
 [6.97937567e-09]
 [4.74508368e-13]
 [2.83092305e-12]
 [7.03954285e-13]
 [9.66438068e-12]
 [8.77662181e-12]
 [1.35871135e-12]
 [4.36797826e-10]
 [3.02371343e-12]
 [4.53503049e-13]
 [6.08371572e-13]
 [6.53424098e-09]
 [5.57028491e-13]
 [5.60223430e-13]
 [6.41237998e-13]
 [1.41418024e-08]
 [1.27498319e-12]
 [5.85430587e-13]
 [9.56754960e-13]
 [4.32141417e-09]
 [3.41419751e-12]
 [7.33016991e-13]
 [3.78563484e-13]
 [2.92727419e-10]
 [4.71908420e-12]
 [7.23487804e-12]
 [6.02465818e-12]
 [4.67409370e-13]
 [7.14950625e-13]
 [1.74766432e-08]
 [1.64939631e-12]
 [4.97789037e-13]
 [1.48563383e-13]
 [9.83104433e-09]
 [6.15827711e-07]
 [4.362302

## Stretch Goals:

- Research "backpropagation" to learn how weights get updated in neural networks (tomorrow's lecture). 
- Implement a multi-layer perceptron. (for non-linearly separable classes)
- Try and implement your own backpropagation algorithm.
- What are the pros and cons of the different activation functions? How should you decide between them for the different layers of a neural network?